# Package CI workflow
# cf. https://docs.astral.sh/uv/guides/integration/github/

name: auto-appearance-ci
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - "3.11"
          - "3.12"
          - "3.13"
    steps:
      - uses: actions/checkout@v4

      - name: Install uv and set the python version
        uses: astral-sh/setup-uv@v6
        with:
          python-version: ${{ matrix.python-version }} 
          enable-cache: true

      - name: Install the project
        run: uv sync --locked --all-extras --dev

      - name: Run linting
        run: uv run ruff check src

      - name: Run type checking
        run: uv run ty check src
